language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev libboost-wave1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-filesystem1.48-dev
script:
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - make test
